In [1]:
#importing libraries

import matplotlib.pyplot as plt
import numpy as np
import bokeh
import requests
import pandas as pd
import datetime
from bokeh.plotting import figure, show, output_file

In [12]:
#Code to obtain trade data for AAPL
API_KEY = '_Fjzwen5ERibsCY-wTsn'
stock_name = 'AAPL.O'
r = requests.get('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=' + stock_name + '&apikey=' + API_KEY)
print(r.status_code)
result = r.json()
data = pd.read_csv(r'C:\Users\Administrateur\Downloads\daily_IBM.csv')
data

200

     timestamp    open    high       low   close   volume
0   2020-12-24  125.00  125.10  124.2100  124.69  1761122
1   2020-12-23  123.88  125.21  123.7400  123.90  2693889
2   2020-12-22  123.31  124.22  122.4100  123.61  4337757
3   2020-12-21  123.97  124.18  121.7200  123.39  6115671
4   2020-12-18  125.59  126.40  124.9700  125.85  7552845
..         ...     ...     ...       ...     ...      ...
95  2020-08-11  128.76  130.47  126.6100  126.75  5001176
96  2020-08-10  125.42  127.24  125.1849  127.11  3968295
97  2020-08-07  123.50  125.07  123.2100  124.96  3651226
98  2020-08-06  125.00  126.26  125.0000  126.12  3417131
99  2020-08-05  126.73  126.75  124.6100  125.45  3675400

[100 rows x 6 columns]

In [8]:
result

{'Error Message': 'Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY.'}

In [ ]:
#convert to dataframe
df = pd.DataFrame.from_dict(dataForAllDays, orient='index') 
df = df.reset_index()
#rename columns
df = df.rename(index=str, columns={"index": "date", "1. open": "open", "2. high": "high", "3. low": "low", "4. close": "close","5. volume":"volume"})
#Changing to datetime
df['date'] = pd.to_datetime(df['date'])
#Sort according to date
df = df.sort_values(by=['date'])
#Changing the datatype 
df.open = df.open.astype(float)
df.close = df.close.astype(float)
df.high = df.high.astype(float)
df.low = df.low.astype(float)
df.volume = df.volume.astype(int)
#check the data
df.head()
#Check the datatype
df.info()

In [ ]:
#display visualization using Bokeh

inc = df.close > df.open
dec = df.open > df.close
w = 12*60*60*1000 # half day in ms
TOOLS = "pan,wheel_zoom,box_zoom,reset,save"
title = stock_name + ' Chart'
p = figure(x_axis_type="datetime", tools=TOOLS, plot_width=1000, title = title)
p.xaxis.major_label_orientation = np.pi/4
p.grid.grid_line_alpha=0.3
p.segment(df.date, df.high, df.date, df.low, color="black")
p.vbar(df.date[inc], w, df.open[inc], df.close[inc], fill_color="#D5E1DD", line_color="black")
p.vbar(df.date[dec], w, df.open[dec], df.close[dec], fill_color="#F2583E", line_color="black")
#Store as a HTML file
output_file("stock_information.html", title="candlestick.py example")
# Display in browser
show(p)

In [ ]:
import urllib.request, urllib.parse, urllib.error
import json

def DailyData(symb):

    url = https://www.alphavantage.co/queryfunction=TIME_SERIES_DAILY&symbol='MSFT.O'&apikey=demo'

    stockdata = urllib.request.urlopen(url)
    data = stockdata.read().decode()

    try:
        js = json.loads(data)
    except:
        js = None

    jstring = 'Time Series (Daily)'

    for entry in js:
        i = js[jstring].keys()

        for jkeys in i:
            return (jkeys,
                js[jstring][jkeys]['1. open'],
                js[jstring][jkeys]['2. high'],
                js[jstring][jkeys]['3. low'],
                js[jstring][jkeys]['4. close'],
                js[jstring][jkeys]['5. volume'])

print('volume',DailyData(symbol)[5])

In [ ]:
pip install pandas_datareader

In [ ]:
#importing libraries

import matplotlib.pyplot as plt
import numpy as np
import bokeh
import requests
import pandas as pd
import datetime
from bokeh.plotting import figure, show, output_file

from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Define the instruments to download. We would like to see Apple, Microsoft and the S&P500 index.
tickers = ['AAPL', 'MSFT', '^GSPC']

# We would like all available data from 01/01/2000 until 12/31/2016.
start_date = '2016-01-01'
end_date = '2020-12-31'

# User pandas_reader.data.DataReader to load the desired data. As simple as that.
panel_data = data.DataReader('INPX', 'yahoo', start_date, end_date)

In [ ]:
panel_data.to_frame().head(9)

In [ ]:
pip install bs4

In [2]:
pip install BeautifulSoup4

Requirement already satisfied: BeautifulSoup4 in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (4.9.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (from BeautifulSoup4) (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [5]:
from bs4 import BeautifulSoup
#import BeautifulSoup4 

#import requests from BeautifulSoup4
import requests

import csv 
import pandas as pd

In [21]:
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
for i in range(0,10):
    CryptoCurrenciesUrl = "https://in.finance.yahoo.com/cryptocurrencies?offset="+str(i)+"&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;count=50"
    r= requests.get(CryptoCurrenciesUrl)
    data=r.text
    soup=BeautifulSoup(data)
 
    for listing in soup.find_all('tr', attrs={'class':'SimpleDataTableRow'}):
        for name in listing.find_all('td', attrs={'aria-label':'Name'}):
            names.append(name.text)
        for price in listing.find_all('td', attrs={'aria-label':'Price (intraday)'}):
            prices.append(price.find('span').text)
        for change in listing.find_all('td', attrs={'aria-label':'Change'}):
            changes.append(change.text)
        for percentChange in listing.find_all('td', attrs={'aria-label':'% change'}):
            percentChanges.append(percentChange.text)
        for marketCap in listing.find_all('td', attrs={'aria-label':'Market cap'}):
            marketCaps.append(marketCap.text)
        for totalVolume in listing.find_all('td', attrs={'aria-label':'Total volume all currencies (24 hrs)'}):
            totalVolumes.append(totalVolume.text)
        for circulatingSupply in listing.find_all('td', attrs={'aria-label':'Circulating supply'}):
            circulatingSupplys.append(circulatingSupply.text)
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/currencies"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
    for listing in soup.find_all('tr', attrs={'data-reactid':i}):
          for name in listing.find_all('td', attrs={'data-reactid':i+3}):
            names.append(name.text)
            for price in listing.find_all('td', attrs={'data-reactid':i+4}):
                    prices.append(price.text)
            for change in listing.find_all('td', attrs={'data-reactid':i+5}):
                changes.append(change.text)
            for percentChange in listing.find_all('td', attrs={'data-reactid':i+7}):
                percentChanges.append(percentChange.text)
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges})

In [22]:
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/currencies"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
    for listing in soup.find_all('tr', attrs={'data-reactid':i}):
          for name in listing.find_all('td', attrs={'data-reactid':i+3}):
            names.append(name.text)
            for price in listing.find_all('td', attrs={'data-reactid':i+4}):
                    prices.append(price.text)
            for change in listing.find_all('td', attrs={'data-reactid':i+5}):
                changes.append(change.text)
            for percentChange in listing.find_all('td', attrs={'data-reactid':i+7}):
                percentChanges.append(percentChange.text)
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges})

      Names       Prices    Change % Change
0   USD/INR      73.6020   +0.2120   +0.29%
1   EUR/INR      87.3298   +0.2080   +0.24%
2   GBP/INR      94.8291   +0.5621   +0.60%
3   AED/INR      19.9930   +0.0550   +0.28%
4   INR/JPY       1.4287   -0.0087   -0.61%
5   SGD/INR      54.1040   +0.3070   +0.57%
6   USD/IDR  14,835.0000  -25.0000   -0.17%
7   USD/THB      31.2200   -0.0700   -0.22%
8   USD/MYR       4.1280   -0.0150   -0.36%
9   USD/ZAR      16.4918   -0.1458   -0.88%
10  USD/RUB      75.0913   -0.1976   -0.26%
11  AUD/USD       0.7322   +0.0028   +0.39%
12  AUD/JPY      77.1340   +0.0900   +0.12%
13  NZD/USD       0.6724   +0.0019   +0.29%
14  EUR/USD       1.1855   -0.0014   -0.12%
15  EUR/CAD       1.5609   -0.0023   -0.15%
16  USD/JPY     105.3910   -0.3040   -0.29%
17  GBP/USD       1.2887   +0.0034   +0.27%
18  USD/CHF       0.9074   -0.0009   -0.10%
19  USD/CAD       1.3169   -0.0005   -0.04%
20  EUR/JPY     124.9060   -0.5140   -0.41%
21  GBP/JPY     135.7740   -0.0160   -0.01%
22  EUR/GBP       0.9199   -0.0035   -0.38%
23  EUR/SEK      10.4083   +0.0062   +0.06%
24  EUR/CHF       1.0756   -0.0017   -0.16%
25  EUR/HUF     357.2750   +0.2150   +0.06%

In [23]:
prices=[]
names=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/world-indices"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
   for row in soup.find_all('tbody'):
      for srow in row.find_all('tr'):
         for name in srow.find_all('td', attrs={'class':'data-col1'}):
            names.append(name.text)
         for price in srow.find_all('td', attrs={'class':'data-col2'}):
            prices.append(price.text)
         for change in srow.find_all('td', attrs={'class':'data-col3'}):
            changes.append(change.text)
         for percentChange in srow.find_all('td', attrs={'class':'data-col4'}):
            percentChanges.append(percentChange.text)
 
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges})

                         Names     Prices   Change % Change
0                   BSE SENSEX  39,044.35  +287.72   +0.74%
1                     Nifty 50  11,521.80   +81.75   +0.71%
2                          Dow  28,166.77  +173.44   +0.62%
3                       Nasdaq  11,228.30  +171.65   +1.55%
4                       Nikkei  23,454.89  -104.41   -0.44%
..                         ...        ...      ...      ...
931                     MERVAL  38,390.84  +233.89   +0.61%
932                     TA-125   1,370.99    +8.48   +0.62%
933  EGX 30 Price Return Index  11,028.10    -6.30   -0.06%
934   Top 40 USD Net TRI Index   3,383.96   +35.33   +1.06%
935     S&P/NZX 50 INDEX GROSS  11,770.75   -19.79   -0.17%

[936 rows x 4 columns]

In [6]:
pip install requests

Requirement already satisfied: requests in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (2.23.0)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (from requests) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (from requests) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\administrateur\appdata\local\programs\python\python38-32\lib\site-packages (from requests) (1.25.8)

In [ ]:
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
import requests
from bs4 import BeautifulSoup
for i in range(0,11):
    CryptoCurrenciesUrl = "https://in.finance.yahoo.com/most-active?offset="+str(i)+"&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;count=100"
    r= requests.get(CryptoCurrenciesUrl)
    data=r.text
    soup=BeautifulSoup(data)
 
for listing in soup.find_all('tr', attrs={'class':'SimpleDataTableRow'}):
   for name in listing.find_all('td', attrs={'aria-label':'Name'}):
      names.append(name.text)
   for price in listing.find_all('td', attrs={'aria-label':'Price (intraday)'}):
      prices.append(price.find('span').text)
   for change in listing.find_all('td', attrs={'aria-label':'Change'}):
      changes.append(change.text)
   for percentChange in listing.find_all('td', attrs={'aria-label':'% change'}):
      percentChanges.append(percentChange.text)
   for marketCap in listing.find_all('td', attrs={'aria-label':'Market cap'}):
      marketCaps.append(marketCap.text)
   for totalVolume in listing.find_all('td', attrs={'aria-label':'Avg vol (3-month)'}):
      totalVolumes.append(totalVolume.text)
   for circulatingSupply in listing.find_all('td', attrs={'aria-label':'Volume'}):
      circulatingSupplys.append(circulatingSupply.text)
 
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges, "Market Cap": marketCaps, "Average Volume": totalVolumes,"Volume":circulatingSupplys})

In [1]:
prices=[]
names=[]
changes=[]
percentChanges=[]
marketCaps=[]
marketTimes=[]
totalVolumes=[]
openInterests=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/commodities"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
counter = 40
for i in range(40, 404, 14):
        for row in soup.find_all('tbody'):
            for srow in row.find_all('tr'):
                for name in srow.find_all('td', attrs={'class':'data-col1'}):
                    names.append(name.text)
                for price in srow.find_all('td', attrs={'class':'data-col2'}):
                    prices.append(price.text)
                for time in srow.find_all('td', attrs={'class':'data-col3'}):
                    marketTimes.append(time.text)
                for change in srow.find_all('td', attrs={'class':'data-col4'}):
                    changes.append(change.text)
                for percentChange in srow.find_all('td', attrs={'class':'data-col5'}):
                    percentChanges.append(percentChange.text)
                for volume in srow.find_all('td', attrs={'class':'data-col6'}):
                    totalVolumes.append(volume.text)
                for openInterest in srow.find_all('td', attrs={'class':'data-col7'}):
                    openInterests.append(openInterest.text)

pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges, "Market Time": marketTimes,'Open Interest': openInterests ,"Volume": totalVolumes})

NameError: name 'requests' is not defined